# Render Blueprint for Infrastructure as Code
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: email-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class=uvicorn.workers.UvicornWorker --workers=2 --bind 0.0.0.0:$PORT email_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: GUNICORN_CMD_ARGS
        value: "--workers=2 --worker-class=uvicorn.workers.UvicornWorker --timeout 120"
      - key: DATABASE_URL
        fromService:
          name: email-db
          type: postgres
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

  - type: worker
    name: imap-poller
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python -u imap_poller.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromService:
          name: email-db
          type: postgres
          property: connectionString
      - key: DJANGO_SECRET_KEY
        sync: true
      # Application settings
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: TZ
        value: "UTC"
      # Logging
      - key: LOG_LEVEL
        value: "DEBUG"
      - key: LOG_DIR
        value: "/tmp/logs"
    autoDeploy: true
